export const REGISTER_USER = 'REGISTER_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const GET_USER = 'GET_USER'
export const EDIT_USER = 'EDIT_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const PAGINATION = 'PAGINATION'
export const SORT_ASC = 'SORT_ASC' 
export const SORT_DSC = 'SORT_DSC'
export const SEARCH_FIELD = 'SEARCH_FIELD'
// export const COUNTRY = 'COUNTRY'
// export const STATE = 'STATE'
// export const CITY = 'CITY' 

